Add clang
comp-prog-jp-library-standard/competitive-programming-library pull request #37
Opened 2018-10-15 03:52 UTC by beet-aizu

GCCとClangの両方でテストするようにしました。バージョンとオプションはAtCoderに揃えています。

2018-10-15 13:29 UTC, asi1024 requested changes

2018-10-15 13:29 UTC, asi1024 commented on .travis.yml
> +    - GCC_CXX=g++
ここを `g++-5` にしてしまえば下で symlink を張る作業が要らなくなる

2018-10-15 13:29 UTC, asi1024 commented on .travis.yml
> +    - clang++-3.8
g++ 用と clang 用で2つのテストのジョブを作るようにする

2018-10-15 13:29 UTC, asi1024 commented on bin/test.py
> +        # GCC
環境変数がセットされていないときのデフォルトの動作

2018-10-15 13:29 UTC, asi1024 commented on bin/test.py
> +            '{} {} main.cpp -o ./a.out'.format(compiler, options))
ここの行が C++ 前提で動いている以上は，環境変数を参照する処理をここに移した方がよい
(あるいは，ここを多言語対応するか)

2018-10-15 13:29 UTC, asi1024 commented on bin/test.py
> +        self.show_result('OK', input_path.name, time_duration, 'green')
ここの変更の意図は何ですか？
(ここを変更するのなら他の `show_result` の呼び出しも変えるべき)

2018-10-15 13:29 UTC, asi1024 commented on bin/test.py
> +        source_path.touch(mode=0o666, exist_ok=True)
コンパイルの度に sandbox を作り直すべきなので，exist_ok は False にしてください．

2018-10-15 14:16 UTC, beet-aizu commented on bin/test.py
> +        self.show_result('OK', input_path.name, time_duration, 'green')
DSL_1_A(gcc)みたいな表示にしたかったので型をstrにしたかったんですがジョブを分けるなら必要ないので修正します

2018-10-15 14:18 UTC, asi1024 commented on bin/test.py
> +        self.show_result('OK', input_path.name, time_duration, 'green')
なるほど，わかりました

2018-10-21 06:07 UTC, asi1024 requested changes

2018-10-21 06:07 UTC, asi1024 commented on .travis.yml
>      packages:
GCCとClangのテストでそれぞれ両方インストールされてしまっています．

2018-10-21 06:07 UTC, asi1024 commented on bin/test.py
> +        compiler = os.getenv('CXX')
CXXのデフォルトは `g++` にしてしまってよいと思います

2018-10-21 06:07 UTC, asi1024 commented on bin/test.py
> +        options = os.getenv('CXX_FLAGS', '')
これも， `--std=c++14 -O2 -Wall` とか？

2018-10-21 06:49 UTC, beet-aizu commented on .travis.yml
>      packages:
ubuntu-toolchain-r-testにはclang-formatが入っていないようなので両方で必要そうです。

2018-10-21 06:51 UTC, beet-aizu commented on .travis.yml
>      packages:
clang-3.8の依存に入っているlibllvmとlibstdc++のバージョンがclang-format-6.0のバージョンとずれているのでpackagesに追加する必要がありそうです。　参考：https://travis-ci.org/comp-prog-jp-library-standard/competitive-programming-library/jobs/444281175

2018-10-21 06:52 UTC, beet-aizu commented on .travis.yml
>      packages:
僕の意見としてはこのまま（gccとclangのテストでそれぞれ両方インストールする）にするのがわかりやすい気がします

2018-10-23 17:42 UTC, asi1024 commented on .travis.yml
>      packages:
とりあえずは動くのでmergeします

2018-10-23 17:43 UTC, asi1024 approved these changes

2018-10-23 17:43 UTC, merged

2018-10-23 17:54 UTC, asi1024 commented
Resolved #33.